# Makefile autogenerated by premake
# Options:
#   CONFIG=[Debug|Release]

ifndef CONFIG
  CONFIG=Debug
endif

export CONFIG

.PHONY: all clean a2e obj2a2m chat-server gui model

all: a2e obj2a2m chat-server gui model

Makefile: ./premake.lua ./src/premake.lua ./tools/premake.lua ./samples/chat/premake.lua ./samples/gui/premake.lua ./samples/model/premake.lua
	@echo ==== Regenerating Makefiles ====
	@premake --target gnu --target vs6 --target vs2003

a2e:
	@echo ==== Building a2e ====
	@$(MAKE) --no-print-directory -C ./src/
obj2a2m:
	@echo ==== Building obj2a2m ====
	@$(MAKE) --no-print-directory -C ./tools/
chat-server: a2e
	@echo ==== Building chat-server ====
	@$(MAKE) --no-print-directory -C ./samples/chat/
gui: a2e
	@echo ==== Building gui ====
	@$(MAKE) --no-print-directory -C ./samples/gui/
model: a2e
	@echo ==== Building model ====
	@$(MAKE) --no-print-directory -C ./samples/model/
clean:
	@$(MAKE) --no-print-directory -C ./src/ clean
	@$(MAKE) --no-print-directory -C ./tools/ clean
	@$(MAKE) --no-print-directory -C ./samples/chat/ clean
	@$(MAKE) --no-print-directory -C ./samples/gui/ clean
	@$(MAKE) --no-print-directory -C ./samples/model/ clean
